/* ===========================================================================
 * SPENDING CYCLES
 * ---------------------------------------------------------------------------
 * A cycle is any half-open interval [start, end). Slice 2 uses calendar
 * months, but nothing here assumes that — the paycheck-cadence gap the
 * research identifies is a real one, and a period that knows its own start
 * and end can be generated by a different rule later without any of the
 * arithmetic below changing.
 * ======================================================================== */

export interface Cycle {
  /** Inclusive, 'YYYY-MM-DD'. */
  start: string;
  /** Inclusive, 'YYYY-MM-DD'. The last day money still counts as this cycle. */
  end: string;
  /** Total days in the cycle, counting both ends. */
  totalDays: number;
  /** Days from the start up to and including today. At least 1. */
  elapsedDays: number;
  /** Days left after today, including today. At least 0. */
  remainingDays: number;
}

const MS_PER_DAY = 86_400_000;

export function toIsoDate(date: Date): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

export function fromIsoDate(iso: string): Date {
  const [year, month, day] = iso.split('-').map(Number);
  // Local, not UTC: a cycle boundary is a calendar day where the user is.
  return new Date(year ?? 1970, (month ?? 1) - 1, day ?? 1);
}

/** Whole days between two dates, ignoring the time of day. */
export function daysBetween(from: string, to: string): number {
  return Math.round((fromIsoDate(to).getTime() - fromIsoDate(from).getTime()) / MS_PER_DAY);
}

export function addDays(iso: string, days: number): string {
  const date = fromIsoDate(iso);
  date.setDate(date.getDate() + days);
  return toIsoDate(date);
}

/** The calendar month containing `today`. */
export function monthCycle(today: string): Cycle {
  const date = fromIsoDate(today);
  const start = new Date(date.getFullYear(), date.getMonth(), 1);
  const end = new Date(date.getFullYear(), date.getMonth() + 1, 0);

  const totalDays = daysBetween(toIsoDate(start), toIsoDate(end)) + 1;
  const elapsedDays = Math.min(totalDays, Math.max(1, daysBetween(toIsoDate(start), today) + 1));

  return {
    start: toIsoDate(start),
    end: toIsoDate(end),
    totalDays,
    elapsedDays,
    remainingDays: Math.max(0, totalDays - elapsedDays + 1),
  };
}

/** Every date in the cycle, in order. Used as the horizontal axis. */
export function cycleDays(cycle: Cycle): string[] {
  const days: string[] = [];
  for (let i = 0; i < cycle.totalDays; i++) days.push(addDays(cycle.start, i));
  return days;
}
